import React from 'react';

const ImagePreloader = () => {
    React.useEffect(() => {
        const imagesToPreload = [
            '/images/M_belly 1.svg',
            '/images/W_belly 1.svg',
            "/images/M_breasts 1.svg",
            "/images/W_breasts 1.svg",
            "/images/M_buttocks 1.svg",
            "/images/W_buttocks 1.svg",
            "/images/snooze.png",
            "/images/M_average 1.svg",
            "/images/W_average 1.svg",
            "/images/M_plump 1.svg",
            "/images/W_plump 1.svg",
            "/images/M_extra 1.svg",
            "/images/W_extra 1.svg",
            "/images/gender_female_icon.svg",
            "/images/gender_male_icon.svg",
            "/images/gender_other_icon.svg",
            "/images/acrobat.png",
            "/images/runGirl.png",
            "/images/redHeart.png",
            "/images/M_fit 1.svg",
            "/images/W_fit 1.svg",
            "/images/M_average 2.svg",
            "/images/W_average 2.svg",
            "/images/M_athletic 1.svg",
            "/images/W_athletic 1.svg",
            "/images/funny.png",
            "/images/littleFunny.png",
            "/images/sad.png",
            "/images/stop.png",
            "/images/before7am.png",
            "/images/carrot.png",
            "/images/eggs.png",
            "/images/plate.png",
            "/images/burger.png",
            "/images/noodles.png",
            "/images/soup.png",
            "/images/plate.png",
            "/images/potato.png",
            "/images/plov.png",
            "/images/chicken.png",
            "/images/plate.png",
            "/images/house.png",
            "/images/box.png",
            "/images/rock.png",
            "/images/like.png",
            "/images/ok.png",
            "/images/stop.png",
            "/images/like.png",
            "/images/sun.png",
            "/images/halfMoon.png",
            "/images/time.png",
            "/images/palm.png",
            "/images/runMan.png",
            "/images/turtle.png",
            "/images/frustrated.png",
            "/images/sadAndCry.png",
            "/images/strong.png",
            "/images/drop.png",
            "/images/manyDrops.png",
            "/images/coolMan.png",
            "/images/coffee.png",
            "/images/yawn.png",
            "/images/sleepe.png",
            "/images/bad.png",
            "/images/zzz.png",
            "/images/pregnant.png",
            "/images/noGirl.png",
            "/images/yellow.png",
            "/images/vitamin.png",
            "/images/hormones.png",
            "/images/bactery.png",
            "/images/coctail.png",
            "/images/chocolate.png",
            "/images/salt.png",
            "/images/moon.png",
            "/images/marriage.png",
            "/images/boom.png",
            "/images/vitamin.png",
            "/images/busy.png",
            "/images/pregnant.png",
            "/images/stop.png",
            "/images/thinking.png",
            "/images/eyes.png",
            "/images/thunder.png",
        ];
        imagesToPreload.forEach(src => {
            const img = new Image();
            img.src = src;
        });
    }, []);

    return null; 
};

export default ImagePreloader;